@echo off
setlocal enabledelayedexpansion

REM Run VidBeast from Source on Windows
REM Auto-generated by port fix operation - 2026-02-08

REM ═══════════════════════════════════════════════════════════
REM PORT CONFIGURATION
REM ═══════════════════════════════════════════════════════════
set DEV_SERVER_PORT=56813
set ELECTRON_DEBUG_PORT=60799
set ELECTRON_INSPECT_PORT=61129

REM ═══════════════════════════════════════════════════════════
REM COLOR CODES
REM ═══════════════════════════════════════════════════════════
set RED=[91m
set GREEN=[92m
set BLUE=[94m
set YELLOW=[93m
set NC=[0m

echo.
echo %BLUE%[%TIME%]%NC% Starting VidBeast from source (Windows)...
echo.

REM ═══════════════════════════════════════════════════════════
REM PROCESS CLEANUP
REM ═══════════════════════════════════════════════════════════
echo %BLUE%[%TIME%]%NC% Cleaning up zombie processes...

REM Kill zombie electron processes
taskkill /F /IM electron.exe >nul 2>&1

REM Kill processes on configured ports
for %%P in (%DEV_SERVER_PORT% %ELECTRON_DEBUG_PORT% %ELECTRON_INSPECT_PORT%) do (
    for /f "tokens=5" %%A in ('netstat -aon ^| findstr :%%P') do (
        echo %YELLOW%[%TIME%] !%NC% Killing process on port %%P (PID: %%A)
        taskkill /F /PID %%A >nul 2>&1
    )
)

timeout /t 1 /nobreak >nul
echo %GREEN%[%TIME%] OK%NC% Cleanup complete
echo.

REM ═══════════════════════════════════════════════════════════
REM DEPENDENCY CHECK
REM ═══════════════════════════════════════════════════════════
echo %BLUE%[%TIME%]%NC% Checking dependencies...

where node >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo %RED%[%TIME%] X%NC% Node.js is not installed. Download from: https://nodejs.org/
    pause
    exit /b 1
)

where npm >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo %RED%[%TIME%] X%NC% npm is not installed
    pause
    exit /b 1
)

for /f "delims=" %%V in ('node --version') do set NODE_VERSION=%%V
for /f "delims=" %%V in ('npm --version') do set NPM_VERSION=%%V
echo %GREEN%[%TIME%] OK%NC% Dependencies OK (Node: %NODE_VERSION%, npm: %NPM_VERSION%)
echo.

REM ═══════════════════════════════════════════════════════════
REM INSTALL DEPENDENCIES
REM ═══════════════════════════════════════════════════════════
if not exist "node_modules" (
    echo %BLUE%[%TIME%]%NC% Installing dependencies...
    call npm install
    if %ERRORLEVEL% NEQ 0 (
        echo %RED%[%TIME%] X%NC% Failed to install dependencies
        pause
        exit /b 1
    )
)

REM ═══════════════════════════════════════════════════════════
REM ENVIRONMENT CONFIGURATION
REM ═══════════════════════════════════════════════════════════
set ELECTRON_NO_ATTACH_CONSOLE=1

echo.
echo %BLUE%[%TIME%]%NC% Port Configuration:
echo   DEV_SERVER_PORT:       %GREEN%%DEV_SERVER_PORT%%NC%
echo   ELECTRON_DEBUG_PORT:   %GREEN%%ELECTRON_DEBUG_PORT%%NC%
echo   ELECTRON_INSPECT_PORT: %GREEN%%ELECTRON_INSPECT_PORT%%NC%
echo.

REM ═══════════════════════════════════════════════════════════
REM RUN APPLICATION
REM ═══════════════════════════════════════════════════════════
echo %BLUE%[%TIME%]%NC% Launching application...
call npm run dev

echo.
echo %GREEN%[%TIME%] OK%NC% Application session ended
pause
