#!/bin/bash

# Run VidBeast from Source on macOS
# Auto-generated by port fix operation - 2026-02-08

# ═══════════════════════════════════════════════════════════
# PORT CONFIGURATION
# ═══════════════════════════════════════════════════════════
DEV_SERVER_PORT=56813
ELECTRON_DEBUG_PORT=60799
ELECTRON_INSPECT_PORT=61129

# ═══════════════════════════════════════════════════════════
# COLOR CODES
# ═══════════════════════════════════════════════════════════
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

print_status() {
    echo -e "${BLUE}[$(date +'%H:%M:%S')]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[$(date +'%H:%M:%S')] ✔${NC} $1"
}

print_error() {
    echo -e "${RED}[$(date +'%H:%M:%S')] ✗${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[$(date +'%H:%M:%S')] ⚠${NC} $1"
}

# ═══════════════════════════════════════════════════════════
# PROCESS CLEANUP
# ═══════════════════════════════════════════════════════════
cleanup_processes() {
    print_status "Cleaning up zombie processes..."

    # Kill zombie electron processes
    pkill -9 -f "Electron.*vid-beast" 2>/dev/null
    pkill -9 -f "Electron.*vidbeast" 2>/dev/null
    pkill -9 -f "electron.*vid-beast" 2>/dev/null

    # Kill processes on configured ports
    for port in $DEV_SERVER_PORT $ELECTRON_DEBUG_PORT $ELECTRON_INSPECT_PORT; do
        local pid=$(lsof -ti:$port 2>/dev/null)
        if [ ! -z "$pid" ]; then
            print_warning "Killing process on port $port (PID: $pid)"
            kill -9 $pid 2>/dev/null
        fi
    done

    sleep 1
    print_success "Cleanup complete"
}

# ═══════════════════════════════════════════════════════════
# DEPENDENCY CHECK
# ═══════════════════════════════════════════════════════════
check_dependencies() {
    print_status "Checking dependencies..."

    if ! command -v node >/dev/null 2>&1; then
        print_error "Node.js is not installed. Install from: https://nodejs.org/"
        exit 1
    fi

    if ! command -v npm >/dev/null 2>&1; then
        print_error "npm is not installed. Install from: https://nodejs.org/"
        exit 1
    fi

    print_success "Dependencies OK (Node: $(node --version), npm: $(npm --version))"
}

# ═══════════════════════════════════════════════════════════
# MAIN EXECUTION
# ═══════════════════════════════════════════════════════════

# Check if we're on macOS
if [ "$(uname)" != "Darwin" ]; then
    print_error "This script is for macOS only"
    exit 1
fi

print_status "🚀 Starting VidBeast from source (macOS)..."
echo ""

# Cleanup processes
cleanup_processes

# Check dependencies
check_dependencies

# Install dependencies if needed
if [ ! -d "node_modules" ]; then
    print_status "Installing dependencies..."
    npm install
    if [ $? -ne 0 ]; then
        print_error "Failed to install dependencies"
        exit 1
    fi
fi

# Set Electron environment variables
export ELECTRON_NO_ATTACH_CONSOLE=1

# Export port configuration
export DEV_SERVER_PORT=$DEV_SERVER_PORT
export ELECTRON_DEBUG_PORT=$ELECTRON_DEBUG_PORT
export ELECTRON_INSPECT_PORT=$ELECTRON_INSPECT_PORT

echo ""
print_status "Port Configuration:"
echo -e "  DEV_SERVER_PORT:       ${GREEN}$DEV_SERVER_PORT${NC}"
echo -e "  ELECTRON_DEBUG_PORT:   ${GREEN}$ELECTRON_DEBUG_PORT${NC}"
echo -e "  ELECTRON_INSPECT_PORT: ${GREEN}$ELECTRON_INSPECT_PORT${NC}"
echo ""

# Run the app
print_status "Launching application..."
npm run dev

# Cleanup on exit
print_success "Application session ended"
